# Generated by Django 4.0.4 on 2022-04-18 17:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('Company_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Comp',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('Contract_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=10)),
                ('Price', models.FloatField()),
                ('Start_Date', models.DateTimeField(auto_now_add=True)),
                ('End_Date', models.DateTimeField(auto_now_add=True)),
                ('Signing_Date', models.DateField(auto_now_add=True)),
                ('Billing_Frequency', models.IntegerField()),
                ('Company', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.companies')),
            ],
            options={
                'verbose_name_plural': 'cid',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('mobile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('Vaccination_Status', models.BooleanField(default=False)),
                ('Vehicle_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Service_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('Shop_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('Slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Slot_status', models.BooleanField(default=False)),
                ('Rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Discount', models.FloatField()),
                ('GST', models.FloatField()),
                ('Date_issued', models.DateTimeField(auto_now_add=True)),
                ('Date_paid', models.DateTimeField(auto_now=True)),
                ('Contract', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.contracts')),
                ('issued_by', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, related_name='company_issuing', to='mall.companies')),
                ('issued_to', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, related_name='company_issued', to='mall.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('out_time', models.DateTimeField(auto_now_add=True)),
                ('Invoice', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mall.invoice')),
                ('Slot', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.slots')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.customer', validators=[django.core.validators.RegexValidator(code='no match', message='should be a valid phone number', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Company_contact_no',
            fields=[
                ('Contact_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='no match', message='should be a valid phone number', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')])),
                ('Company', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mall.companies')),
            ],
            options={
                'unique_together': {('Contact_no', 'Company_id')},
            },
        ),
        migrations.CreateModel(
            name='Provides',
            fields=[
                ('Contract', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mall.contracts')),
                ('Service', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.services')),
            ],
            options={
                'unique_together': {('Contract_id', 'Service_id')},
            },
        ),
        migrations.CreateModel(
            name='Bound_by',
            fields=[
                ('Contract', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mall.contracts')),
                ('Shop', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.shops')),
            ],
            options={
                'unique_together': {('Contract_id', 'Shop_id')},
            },
        ),
    ]
