# Generated by Django 4.0.4 on 2022-04-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('mobile_no', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('Vaccination_Status', models.BooleanField(default=False)),
                ('Vehicle_id', models.CharField(max_length=30)),
            ],
        ),
    ]
