# Generated by Django 4.0.4 on 2022-04-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Invoice',
        ),
        migrations.CreateModel(
            name='ParkingReceipt',
            fields=[
                ('Receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Date_of_issue', models.DateField()),
                ('Booking', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.booking')),
                ('Slot', models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.slots')),
            ],
        ),
    ]
