# Generated by Django 4.0.4 on 2022-04-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='Type',
            field=models.CharField(choices=[('S', 'Selling'), ('R', 'Renting')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shops',
            name='Status',
            field=models.CharField(choices=[('S', 'Sold'), ('R', 'Rented'), ('E', 'Empty')], default='E', max_length=1),
        ),
    ]
