# Generated by Django 4.0.4 on 2022-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('Invoice_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Amount', models.FloatField()),
                ('Discount', models.FloatField()),
                ('GST', models.FloatField()),
                ('Date_issued', models.DateTimeField(auto_now_add=True)),
                ('Date_paid', models.DateTimeField(auto_now=True)),
                ('Contract_id', models.CharField(max_length=40)),
                ('issued_by_id', models.CharField(max_length=40)),
                ('issued_to_id', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='companies',
            name='Company_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
