# Generated by Django 4.0.4 on 2022-04-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_alter_booking_options_alter_bound_by_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
