# Generated by Django 4.0.4 on 2022-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_invoice_alter_companies_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('Contract_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=10)),
                ('Price', models.FloatField()),
                ('Start_Date', models.DateTimeField(auto_now_add=True)),
                ('End_Date', models.DateTimeField(auto_now_add=True)),
                ('Signing_Date', models.DateField(auto_now_add=True)),
                ('Billing_Frequency', models.IntegerField()),
                ('Company_id', models.CharField(max_length=40)),
            ],
        ),
    ]
