# Generated by Django 4.0.4 on 2022-04-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('Shop_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
    ]
