# Generated by Django 4.0.4 on 2022-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_shops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
