# Generated by Django 4.0.4 on 2022-04-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_remove_invoice_totalamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(default='def', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='in_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='out_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='Company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mall.companies'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='End_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='Signing_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='Start_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Date_issued',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Date_paid',
            field=models.DateTimeField(),
        ),
    ]
