# Generated by Django 4.0.4 on 2022-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_adminmodel_alter_booking_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Type',
            field=models.CharField(max_length=30),
        ),
    ]
