# Generated by Django 4.0.4 on 2022-04-16 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_contact_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='no match', message='should be a valid phone number', regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')])),
                ('Company_id', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('Contact_no', 'Company_id')},
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
