# Generated by Django 4.0.4 on 2022-04-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_adminmodel_alter_booking_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Date_paid',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Invoice_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
