# Generated by Django 4.0.4 on 2022-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_alter_services_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contracts',
            name='Contract_id',
            field=models.CharField(max_length=40),
        ),
    ]
