# Generated by Django 4.0.4 on 2022-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_alter_invoice_date_paid_alter_invoice_invoice_id'),
        ('mall', '0007_alter_services_type'),
    ]

    operations = [
    ]
