# Generated by Django 4.0.4 on 2022-04-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_alter_companies_email'),
        ('mall', '0007_alter_services_type'),
    ]

    operations = [
    ]
