# Generated by Django 4.0.4 on 2022-04-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_company_contact_no_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_contact_no',
            name='id',
        ),
        migrations.AlterField(
            model_name='company_contact_no',
            name='Company_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
