# Generated by Django 4.0.4 on 2022-04-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_merge_20220426_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='End_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='Start_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='Type',
            field=models.CharField(choices=[('S', 'Sell'), ('R', 'Rent'), ('T', 'Service')], max_length=1),
        ),
    ]
