# Generated by Django 4.0.4 on 2022-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provides',
            fields=[
                ('Contract_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Service_id', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('Contract_id', 'Service_id')},
            },
        ),
    ]
