# Generated by Django 4.0.4 on 2022-04-26 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_remove_contracts_id_alter_contracts_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_contact_no',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company_contact_no',
            name='Company',
            field=models.ForeignKey(default='def', on_delete=django.db.models.deletion.CASCADE, to='mall.companies'),
        ),
    ]
