# Generated by Django 4.0.4 on 2022-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_provides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Service_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
    ]
