# Generated by Django 4.0.4 on 2022-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bound_by',
            fields=[
                ('Contract_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Shop_id', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('Contract_id', 'Shop_id')},
            },
        ),
    ]
