# Generated by Django 4.0.4 on 2022-04-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_bound_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': 'Comp'},
        ),
    ]
