# Generated by Django 4.0.4 on 2022-04-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0014_alter_companies_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_contact_no',
            name='comp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mall.companies', verbose_name='Comp'),
            preserve_default=False,
        ),
    ]
