# Generated by Django 4.0.4 on 2022-04-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_merge_20220426_1923'),
        ('mall', '0014_alter_bound_by_contract_alter_provides_contract'),
    ]

    operations = [
    ]
