# Generated by Django 4.0.4 on 2022-04-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0015_merge_20220426_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_contact_no',
            name='id',
        ),
        migrations.AddField(
            model_name='company_contact_no',
            name='comp_cont_id',
            field=models.AutoField(primary_key=True, serialize=False),

        ),
    ]
