# Generated by Django 4.0.4 on 2022-04-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0015_company_contact_no_comp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'verbose_name_plural': 'cid'},
        ),
        migrations.RemoveField(
            model_name='company_contact_no',
            name='comp',
        ),
    ]
