# Generated by Django 4.0.4 on 2022-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0016_remove_company_contact_no_id_and_more'),
    ]

    operations = [
        
        
    ]
