# Generated by Django 4.0.4 on 2022-04-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0016_alter_contracts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='Company_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mall.companies'),
        ),
    ]
