# Generated by Django 4.0.4 on 2022-04-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_remove_company_contact_no_comp_cont_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Service_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
