# Generated by Django 4.0.4 on 2022-04-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_remove_company_contact_no_comp_cont_id_and_more'),
    ]

    operations = [

    ]
